### ISSUE TITLE
Vogue roadmap 2021

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#192]
### Upload BALSAMIC and MicroSalt QC results:

BALSAMC and MicroSalt results are missing from VogueDB:

- [ ] Keep track of trended items in clinical-api
- [ ] Define what to plot for these cases

### Expand QC metrics available from bioinformatics workflows

Current we only only have very limited number of QC metrics uploaded to Vogue. This should be easily expandable to include as many as possible. There are challenges how workflows are handling the input data, so standardization is a challenge.

- [ ] Add all Picardtools' metrics to Vogue

### Immediate trending solutions for Lab needs

We need to learn what to plot from which source of data for Lab's needs.

- [ ] Workshop and train Lab personnel to access data and plot their needs
- [ ] Setup development environment for Lab so they can interact with data while permanent plots are agreed upon

### Refactor how to deploy Vogue

- [x] Create container for Vogue: https://github.com/Clinical-Genomics/vogue/issues/195

## Long term development plan:

- [ ] RestAPI for Vogue: easier communication between sources of data and other tools and Vogue
- [ ] Change underlying database design: MongoDB is not does not cater properly for downstream analysis. It is not optimized for trending and model building
- [x] Obviously containerization of Vogue

### Overview page
- QC data (prep, sequencing, analysis)
- Passed/Failed samples
- Specific sample
- Type of sample (FFPE)
- Over a specific time period
- X and Y coverage per sequence type (WGS, WES (or even capture kit)) from Chanjo

### Control samples TGA
- Monitor all control samples

### Frontend and backend:
- Rest APIs
- Better for building graphs
- A single webpage for monitoring trends
- Different version of pipelines
- Degree of solved cases
- Interactive plots
- Reruns:
        - Per pipeline and time
        - Per pipeline and customer
        - Per sample
        - Time since last analysis

### Other instruments and data source:
- Export Ganglia data to Vogue
- Export Nation data to Vogue
- Overview “NGI” like
        - Put in front of sequencing lab and in Vogue
        - Data generated, Seq. type, Nr of samples, Sample type
- Hamilton
        - Runs per day
        - Nr of samples processed per week

**Comment by mayabrandi** [comment]
So happy you are working on this @hassanfa !

**Comment by hassanfa** [comment]
Microsalt upload is done. Now only BALSAMIC is missing.
