### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/vogue#276]
## Description

We had two swedac deviations that were vogue related last year: 

They complained about two things:
1) We had no trening of microbial QC-data
2) We had pore testing of the data - wich in big part come from the lims database.

Non of the two issues are fully fixed yet and should  be taken care of before next swewdac visit at ...

This Project collects all the must haves before the swedac visit.

## Risk assessment

*Is there a need for a risk assessment. If an RA already is in place add link*

## This can be closed when the points marked with (Must) below are checked.

**General**

- [ ] https://github.com/Clinical-Genomics/project-planning/issues/167 **(Must)**

- [x] need go through https://github.com/Clinical-Genomics/vogue/blob/master/vogue/constants/lims_constants.py in detail. Add missing steps. **(Must)**

**Home**

- [ ] fix colors differe between years
- [ ] Translation table for Samples Recieved 
`{'rml' : 'Ready Made Libraries', 'tgs' : 'Target Genome Sequencing', 'wes' : 'Whole Exome Sequencing', 'wgs' : 'Whole Genome Sequencing', 'cov' : 'SARS-CoV-2 Sequencing', 'mic' : 'Microbial Whole Genome Sequencing', 'wts' : 'Whole Transcriptome Sequencing'}`

**turn_around_times**
- [x] [Fix negative values](https://github.com/Clinical-Genomics/vogue/issues/246) **(Must)**

**Prep Micro**

- [ ] Y-axis: Average Final Library Concentration (nM) 

**Prep WGS**

_Library condentration over time_
- [ ] Box med outliers per batch. Batch =sampled from one container id. generated by step: **End repair Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA)**. Protocol: ** TruSeq DNA PCR-free Library Prep**. Y-axis is time but not months.

**Prep Lucigen**

_Library Concentration vs Input Amount_

- [ ] Y-axis: change name to 'Final Library Concentration (nM)'

_Average Library conc over time_

- [ ] Box med outliers per batch. Batch =sampled from one container id. generated by step: **End repair Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA)**. Protocol: ** TruSeq DNA PCR-free Library Prep**. Y-axis is time but not months.
- [ ] Y-axis: change name to 'Average Final Library Concentration (nM)'

**Prep Target Enrichment**

- [x] [Samples missing in 2021 - fix! ](https://github.com/Clinical-Genomics/vogue/issues/244)**(Must)** 
- [ ]  change title and tab to: 'Target Genome Sequencing (exome/panels)'
- [ ] Y-axis: Average Library Size (bp) pre/post-hyb
- [ ] Plot titles: Average Library size over time pre/post-hyb
- [ ] skugga med avvikelser
- [ ] legend title: Sample Source
- [ ] New plots with concentration over time

**Sequencing**

- [ ] Remove many of the metricses. KEEP: %PF R1/R2, Reads PF R1/R2, % Bases >=Q30. **(Must)**
- [x] Find out what % Bases >=Q30 means. It means The percentage of bases with a quality score of 30 or higher.**(Must)**

**Index performance**

- [ ] Find out what unit the y-axis is **(Must)**
- [x] add index groups: 
- IDT for Illumina UDI 10bp Set 3
- IDT for Illumina UDI 10bp Set 4
- IDT for Illumina UDI 10bp Set A/1
- IDT for Illumina UDI 10bp Set B/2
- IDT for Illumina UDI 10bp Set C
- IDT for Illumina UDI 10bp Set D
- IDT DupSeq 10bp Set A
- IDT DupSeq 10bp Set C
- IDT DupSeq 10bp Set D
- IDT DupSeq 10bp Set E

**Genotype**

- [ ] have meeting with Emma

**Bioinfo WGS WES TGA**

- [x] [go through the metrics list.](https://github.com/Clinical-Genomics/vogue/issues/257) **(Must)**
- [ ] split into two sections: WGS and TGS

**Bioinfo Micro QC over time Plot**

- [x] hide outliers **(Must)**
- [x]  fix bug causing unable to switch between qc metrics **(Must)**

**Fraction of untyped Plot** 

- [x] change definition of untyped

**Bioinfo Cov**
- [ ] [covid qc data needs be added to the database](https://github.com/Clinical-Genomics/vogue/issues/238) **(Must)**

## Don't forget

- [ ] Add to corresponding milestone
- [ ] Add prio labels
